import chalk from "chalk";
import { Command } from "commander";
import { input, select, checkbox } from "@inquirer/prompts";
import {createPrompt} from "@inquirer/core";
import fs from "fs-extra"
import path from "path";
import ora from "ora";
import { execSync } from "child_process"
export function registerInitCommand(program: Command){
    program
     .command("init")
     .description("Create a new autoinfra project in the current directory")
     .action(async () => {
        console.log(chalk.cyan("\n⚙️  AutoInfra Initialization Wizard\n"))

        const projectName = await input({
            message: "Project Name: ",
            default: path.basename(process.cwd())
        })

        const cloud = await select({
            message: "Choose your cloud provider",
            choices: [
                {name: "AWS", value: "aws"},
                {name: "GCP", value: "gcp"},
                {name: "Azure", value: "azure"},
            ],
            default: "aws"
        });

        const deployMode = await select({
            message: "Deployment mode",
            choices: [
                {name: "Kubernetes", value: "kubernetes"},
                {name: "Serverless", value: "serverless"},
                {name: "Hybrid", value: "hybrid"}
            ]
        });

        const modules = await checkbox({
            message: "Enables modules: ",
            choices: [
                {name: "autoscaling", value: "autoscaling", checked: true},
                {name: "cost-monitor", value: "cost-monitor"},
                {name: "health-monitor", value: "health-monitor", checked: true},
                {name: "drift-watcher", value: "drift-watcher", checked: true},
                {name: "cron job", value: "cron job"},
                {name: "logging", value: "logging"},
                
            ]
        })
        const language = await select({
            message: "Language preferred",
            choices: [
                {name: "Typescript", value: "typescript"},
                {name: "Python", value: "python"},
                {name: "Go", value: "go"},
            
            ],
            default: "typescript"
        });

        const spinner = ora("Creating project structure...").start();

        try {
            const folders = [
                'infra/terraform',
                'infra/kubernetes',
                'ai/oumi',
                'ai/codemods',
                'kestra/flows',
                'services/api',
                'services/worker',               

            ]

            for (const folder of folders){
                await fs.mkdirp(folder)
            }

            const config = {
                projectName: projectName,
                cloud: cloud,
                deployMode: deployMode,
                language: language,
                modules: modules,
                createdAt: new Date().toISOString()
            };

            await fs.writeJSON("autoinfra.config.json", config, {spaces: 2});

            await fs.writeFile(
                "README.md",
                `# ${projectName}\nGenerated by AutoInfra.\n\nRun:\n\nautoinfra plan`
            );

            await fs.writeFile(
                "ai/oumi/agent_config.yaml",
                `AutoInfra oumi Agent Config
                project: ${projectName}
                cloud: ${cloud}
                self_healing: true
                max_auto_fixes: 3
                `
            );

            await fs.writeFile(
                "kestra/flows/self_heal.yml",
                `id: self_heal_infra
                 namespace: autoinfra
                 tasks:
                    - id: detect
                      type: io.autoinfra.tasks.drift.Detect
                    
                    - id: heal
                      type: io.autoinfra.tasks.drift.Heal`
                 
            );

            if(!fs.existsSync(".git")){
                execSync('git init')
            }
            spinner.succeed("Project Initialized!");

            console.log(`${chalk.green("AutoInfra project created.")}
            Next steps:
            1. Add credentials → ${chalk.yellow("autoinfra auth")}
            2. Generate plan → ${chalk.yellow("autoinfra plan")}
            3. Deploy infra → ${chalk.yellow("autoinfra deploy")}
        `);

        } catch (error) {
            spinner.fail("Failed to initialize AutoInfra project.");
        console.error(chalk.red(error));
        process.exit(1);
            
        }
     });


}